AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  updateDependencies:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::340032650202:role/BeamLambdaExecution'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(4 days)
      Environment:
        Variables:
          BRANCHES: master develop freight-develop hl/gemini-develop gemini-develop
          INSTANCE_TYPE: t2.small
          SUBMODULES: production/newyork production/sfbay production/austin
