// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trip_infromation.proto

package beam.sim.traveltime;

public final class TripInformationProto {
  private TripInformationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RouteInformationElementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:beam_pevs.RouteInformationElement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double travelTime = 1;</code>
     */
    boolean hasTravelTime();
    /**
     * <code>optional double travelTime = 1;</code>
     */
    double getTravelTime();

    /**
     * <code>optional double travelDistance = 2;</code>
     */
    boolean hasTravelDistance();
    /**
     * <code>optional double travelDistance = 2;</code>
     */
    double getTravelDistance();

    /**
     * <code>optional string linkId = 3;</code>
     */
    boolean hasLinkId();
    /**
     * <code>optional string linkId = 3;</code>
     */
    java.lang.String getLinkId();
    /**
     * <code>optional string linkId = 3;</code>
     */
    com.google.protobuf.ByteString
        getLinkIdBytes();
  }
  /**
   * Protobuf type {@code beam_pevs.RouteInformationElement}
   */
  public static final class RouteInformationElement extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:beam_pevs.RouteInformationElement)
      RouteInformationElementOrBuilder {
    // Use RouteInformationElement.newBuilder() to construct.
    private RouteInformationElement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RouteInformationElement(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RouteInformationElement defaultInstance;
    public static RouteInformationElement getDefaultInstance() {
      return defaultInstance;
    }

    public RouteInformationElement getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RouteInformationElement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              travelTime_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              travelDistance_ = input.readDouble();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              linkId_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return beam.sim.traveltime.TripInformationProto.internal_static_beam_pevs_RouteInformationElement_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return beam.sim.traveltime.TripInformationProto.internal_static_beam_pevs_RouteInformationElement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              beam.sim.traveltime.TripInformationProto.RouteInformationElement.class, beam.sim.traveltime.TripInformationProto.RouteInformationElement.Builder.class);
    }

    public static com.google.protobuf.Parser<RouteInformationElement> PARSER =
        new com.google.protobuf.AbstractParser<RouteInformationElement>() {
      public RouteInformationElement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RouteInformationElement(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RouteInformationElement> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TRAVELTIME_FIELD_NUMBER = 1;
    private double travelTime_;
    /**
     * <code>optional double travelTime = 1;</code>
     */
    public boolean hasTravelTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double travelTime = 1;</code>
     */
    public double getTravelTime() {
      return travelTime_;
    }

    public static final int TRAVELDISTANCE_FIELD_NUMBER = 2;
    private double travelDistance_;
    /**
     * <code>optional double travelDistance = 2;</code>
     */
    public boolean hasTravelDistance() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double travelDistance = 2;</code>
     */
    public double getTravelDistance() {
      return travelDistance_;
    }

    public static final int LINKID_FIELD_NUMBER = 3;
    private java.lang.Object linkId_;
    /**
     * <code>optional string linkId = 3;</code>
     */
    public boolean hasLinkId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string linkId = 3;</code>
     */
    public java.lang.String getLinkId() {
      java.lang.Object ref = linkId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          linkId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string linkId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLinkIdBytes() {
      java.lang.Object ref = linkId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        linkId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      travelTime_ = 0D;
      travelDistance_ = 0D;
      linkId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, travelTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, travelDistance_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLinkIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, travelTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, travelDistance_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLinkIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static beam.sim.traveltime.TripInformationProto.RouteInformationElement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static beam.sim.traveltime.TripInformationProto.RouteInformationElement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static beam.sim.traveltime.TripInformationProto.RouteInformationElement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static beam.sim.traveltime.TripInformationProto.RouteInformationElement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static beam.sim.traveltime.TripInformationProto.RouteInformationElement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static beam.sim.traveltime.TripInformationProto.RouteInformationElement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static beam.sim.traveltime.TripInformationProto.RouteInformationElement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static beam.sim.traveltime.TripInformationProto.RouteInformationElement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static beam.sim.traveltime.TripInformationProto.RouteInformationElement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static beam.sim.traveltime.TripInformationProto.RouteInformationElement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(beam.sim.traveltime.TripInformationProto.RouteInformationElement prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code beam_pevs.RouteInformationElement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:beam_pevs.RouteInformationElement)
        beam.sim.traveltime.TripInformationProto.RouteInformationElementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return beam.sim.traveltime.TripInformationProto.internal_static_beam_pevs_RouteInformationElement_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return beam.sim.traveltime.TripInformationProto.internal_static_beam_pevs_RouteInformationElement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                beam.sim.traveltime.TripInformationProto.RouteInformationElement.class, beam.sim.traveltime.TripInformationProto.RouteInformationElement.Builder.class);
      }

      // Construct using beam.sim.traveltime.TripInformationProto.RouteInformationElement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        travelTime_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        travelDistance_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        linkId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return beam.sim.traveltime.TripInformationProto.internal_static_beam_pevs_RouteInformationElement_descriptor;
      }

      public beam.sim.traveltime.TripInformationProto.RouteInformationElement getDefaultInstanceForType() {
        return beam.sim.traveltime.TripInformationProto.RouteInformationElement.getDefaultInstance();
      }

      public beam.sim.traveltime.TripInformationProto.RouteInformationElement build() {
        beam.sim.traveltime.TripInformationProto.RouteInformationElement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public beam.sim.traveltime.TripInformationProto.RouteInformationElement buildPartial() {
        beam.sim.traveltime.TripInformationProto.RouteInformationElement result = new beam.sim.traveltime.TripInformationProto.RouteInformationElement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.travelTime_ = travelTime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.travelDistance_ = travelDistance_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.linkId_ = linkId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof beam.sim.traveltime.TripInformationProto.RouteInformationElement) {
          return mergeFrom((beam.sim.traveltime.TripInformationProto.RouteInformationElement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(beam.sim.traveltime.TripInformationProto.RouteInformationElement other) {
        if (other == beam.sim.traveltime.TripInformationProto.RouteInformationElement.getDefaultInstance()) return this;
        if (other.hasTravelTime()) {
          setTravelTime(other.getTravelTime());
        }
        if (other.hasTravelDistance()) {
          setTravelDistance(other.getTravelDistance());
        }
        if (other.hasLinkId()) {
          bitField0_ |= 0x00000004;
          linkId_ = other.linkId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        beam.sim.traveltime.TripInformationProto.RouteInformationElement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (beam.sim.traveltime.TripInformationProto.RouteInformationElement) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double travelTime_ ;
      /**
       * <code>optional double travelTime = 1;</code>
       */
      public boolean hasTravelTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double travelTime = 1;</code>
       */
      public double getTravelTime() {
        return travelTime_;
      }
      /**
       * <code>optional double travelTime = 1;</code>
       */
      public Builder setTravelTime(double value) {
        bitField0_ |= 0x00000001;
        travelTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double travelTime = 1;</code>
       */
      public Builder clearTravelTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        travelTime_ = 0D;
        onChanged();
        return this;
      }

      private double travelDistance_ ;
      /**
       * <code>optional double travelDistance = 2;</code>
       */
      public boolean hasTravelDistance() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double travelDistance = 2;</code>
       */
      public double getTravelDistance() {
        return travelDistance_;
      }
      /**
       * <code>optional double travelDistance = 2;</code>
       */
      public Builder setTravelDistance(double value) {
        bitField0_ |= 0x00000002;
        travelDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double travelDistance = 2;</code>
       */
      public Builder clearTravelDistance() {
        bitField0_ = (bitField0_ & ~0x00000002);
        travelDistance_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object linkId_ = "";
      /**
       * <code>optional string linkId = 3;</code>
       */
      public boolean hasLinkId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string linkId = 3;</code>
       */
      public java.lang.String getLinkId() {
        java.lang.Object ref = linkId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            linkId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string linkId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLinkIdBytes() {
        java.lang.Object ref = linkId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          linkId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string linkId = 3;</code>
       */
      public Builder setLinkId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        linkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string linkId = 3;</code>
       */
      public Builder clearLinkId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        linkId_ = getDefaultInstance().getLinkId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string linkId = 3;</code>
       */
      public Builder setLinkIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        linkId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:beam_pevs.RouteInformationElement)
    }

    static {
      defaultInstance = new RouteInformationElement(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:beam_pevs.RouteInformationElement)
  }

  public interface TripInformationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:beam_pevs.TripInformation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
     */
    java.util.List<beam.sim.traveltime.TripInformationProto.RouteInformationElement> 
        getRouteInformationElementsList();
    /**
     * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
     */
    beam.sim.traveltime.TripInformationProto.RouteInformationElement getRouteInformationElements(int index);
    /**
     * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
     */
    int getRouteInformationElementsCount();
    /**
     * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
     */
    java.util.List<? extends beam.sim.traveltime.TripInformationProto.RouteInformationElementOrBuilder> 
        getRouteInformationElementsOrBuilderList();
    /**
     * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
     */
    beam.sim.traveltime.TripInformationProto.RouteInformationElementOrBuilder getRouteInformationElementsOrBuilder(
        int index);

    /**
     * <code>optional double departureTime = 2;</code>
     */
    boolean hasDepartureTime();
    /**
     * <code>optional double departureTime = 2;</code>
     */
    double getDepartureTime();

    /**
     * <code>optional double tripTravelTime = 3;</code>
     */
    boolean hasTripTravelTime();
    /**
     * <code>optional double tripTravelTime = 3;</code>
     */
    double getTripTravelTime();

    /**
     * <code>optional double tripTravelDistance = 4;</code>
     */
    boolean hasTripTravelDistance();
    /**
     * <code>optional double tripTravelDistance = 4;</code>
     */
    double getTripTravelDistance();

    /**
     * <code>optional double tripAverageSpeed = 5;</code>
     */
    boolean hasTripAverageSpeed();
    /**
     * <code>optional double tripAverageSpeed = 5;</code>
     */
    double getTripAverageSpeed();
  }
  /**
   * Protobuf type {@code beam_pevs.TripInformation}
   */
  public static final class TripInformation extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:beam_pevs.TripInformation)
      TripInformationOrBuilder {
    // Use TripInformation.newBuilder() to construct.
    private TripInformation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TripInformation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TripInformation defaultInstance;
    public static TripInformation getDefaultInstance() {
      return defaultInstance;
    }

    public TripInformation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TripInformation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                routeInformationElements_ = new java.util.ArrayList<beam.sim.traveltime.TripInformationProto.RouteInformationElement>();
                mutable_bitField0_ |= 0x00000001;
              }
              routeInformationElements_.add(input.readMessage(beam.sim.traveltime.TripInformationProto.RouteInformationElement.PARSER, extensionRegistry));
              break;
            }
            case 17: {
              bitField0_ |= 0x00000001;
              departureTime_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000002;
              tripTravelTime_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000004;
              tripTravelDistance_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000008;
              tripAverageSpeed_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          routeInformationElements_ = java.util.Collections.unmodifiableList(routeInformationElements_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return beam.sim.traveltime.TripInformationProto.internal_static_beam_pevs_TripInformation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return beam.sim.traveltime.TripInformationProto.internal_static_beam_pevs_TripInformation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              beam.sim.traveltime.TripInformationProto.TripInformation.class, beam.sim.traveltime.TripInformationProto.TripInformation.Builder.class);
    }

    public static com.google.protobuf.Parser<TripInformation> PARSER =
        new com.google.protobuf.AbstractParser<TripInformation>() {
      public TripInformation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TripInformation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TripInformation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ROUTEINFORMATIONELEMENTS_FIELD_NUMBER = 1;
    private java.util.List<beam.sim.traveltime.TripInformationProto.RouteInformationElement> routeInformationElements_;
    /**
     * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
     */
    public java.util.List<beam.sim.traveltime.TripInformationProto.RouteInformationElement> getRouteInformationElementsList() {
      return routeInformationElements_;
    }
    /**
     * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
     */
    public java.util.List<? extends beam.sim.traveltime.TripInformationProto.RouteInformationElementOrBuilder> 
        getRouteInformationElementsOrBuilderList() {
      return routeInformationElements_;
    }
    /**
     * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
     */
    public int getRouteInformationElementsCount() {
      return routeInformationElements_.size();
    }
    /**
     * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
     */
    public beam.sim.traveltime.TripInformationProto.RouteInformationElement getRouteInformationElements(int index) {
      return routeInformationElements_.get(index);
    }
    /**
     * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
     */
    public beam.sim.traveltime.TripInformationProto.RouteInformationElementOrBuilder getRouteInformationElementsOrBuilder(
        int index) {
      return routeInformationElements_.get(index);
    }

    public static final int DEPARTURETIME_FIELD_NUMBER = 2;
    private double departureTime_;
    /**
     * <code>optional double departureTime = 2;</code>
     */
    public boolean hasDepartureTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double departureTime = 2;</code>
     */
    public double getDepartureTime() {
      return departureTime_;
    }

    public static final int TRIPTRAVELTIME_FIELD_NUMBER = 3;
    private double tripTravelTime_;
    /**
     * <code>optional double tripTravelTime = 3;</code>
     */
    public boolean hasTripTravelTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double tripTravelTime = 3;</code>
     */
    public double getTripTravelTime() {
      return tripTravelTime_;
    }

    public static final int TRIPTRAVELDISTANCE_FIELD_NUMBER = 4;
    private double tripTravelDistance_;
    /**
     * <code>optional double tripTravelDistance = 4;</code>
     */
    public boolean hasTripTravelDistance() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional double tripTravelDistance = 4;</code>
     */
    public double getTripTravelDistance() {
      return tripTravelDistance_;
    }

    public static final int TRIPAVERAGESPEED_FIELD_NUMBER = 5;
    private double tripAverageSpeed_;
    /**
     * <code>optional double tripAverageSpeed = 5;</code>
     */
    public boolean hasTripAverageSpeed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double tripAverageSpeed = 5;</code>
     */
    public double getTripAverageSpeed() {
      return tripAverageSpeed_;
    }

    private void initFields() {
      routeInformationElements_ = java.util.Collections.emptyList();
      departureTime_ = 0D;
      tripTravelTime_ = 0D;
      tripTravelDistance_ = 0D;
      tripAverageSpeed_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < routeInformationElements_.size(); i++) {
        output.writeMessage(1, routeInformationElements_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(2, departureTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(3, tripTravelTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(4, tripTravelDistance_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(5, tripAverageSpeed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < routeInformationElements_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, routeInformationElements_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, departureTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, tripTravelTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, tripTravelDistance_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, tripAverageSpeed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static beam.sim.traveltime.TripInformationProto.TripInformation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static beam.sim.traveltime.TripInformationProto.TripInformation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static beam.sim.traveltime.TripInformationProto.TripInformation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static beam.sim.traveltime.TripInformationProto.TripInformation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static beam.sim.traveltime.TripInformationProto.TripInformation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static beam.sim.traveltime.TripInformationProto.TripInformation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static beam.sim.traveltime.TripInformationProto.TripInformation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static beam.sim.traveltime.TripInformationProto.TripInformation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static beam.sim.traveltime.TripInformationProto.TripInformation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static beam.sim.traveltime.TripInformationProto.TripInformation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(beam.sim.traveltime.TripInformationProto.TripInformation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code beam_pevs.TripInformation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:beam_pevs.TripInformation)
        beam.sim.traveltime.TripInformationProto.TripInformationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return beam.sim.traveltime.TripInformationProto.internal_static_beam_pevs_TripInformation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return beam.sim.traveltime.TripInformationProto.internal_static_beam_pevs_TripInformation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                beam.sim.traveltime.TripInformationProto.TripInformation.class, beam.sim.traveltime.TripInformationProto.TripInformation.Builder.class);
      }

      // Construct using beam.sim.traveltime.TripInformationProto.TripInformation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRouteInformationElementsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (routeInformationElementsBuilder_ == null) {
          routeInformationElements_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          routeInformationElementsBuilder_.clear();
        }
        departureTime_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        tripTravelTime_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        tripTravelDistance_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        tripAverageSpeed_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return beam.sim.traveltime.TripInformationProto.internal_static_beam_pevs_TripInformation_descriptor;
      }

      public beam.sim.traveltime.TripInformationProto.TripInformation getDefaultInstanceForType() {
        return beam.sim.traveltime.TripInformationProto.TripInformation.getDefaultInstance();
      }

      public beam.sim.traveltime.TripInformationProto.TripInformation build() {
        beam.sim.traveltime.TripInformationProto.TripInformation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public beam.sim.traveltime.TripInformationProto.TripInformation buildPartial() {
        beam.sim.traveltime.TripInformationProto.TripInformation result = new beam.sim.traveltime.TripInformationProto.TripInformation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (routeInformationElementsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            routeInformationElements_ = java.util.Collections.unmodifiableList(routeInformationElements_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.routeInformationElements_ = routeInformationElements_;
        } else {
          result.routeInformationElements_ = routeInformationElementsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.departureTime_ = departureTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tripTravelTime_ = tripTravelTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tripTravelDistance_ = tripTravelDistance_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.tripAverageSpeed_ = tripAverageSpeed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof beam.sim.traveltime.TripInformationProto.TripInformation) {
          return mergeFrom((beam.sim.traveltime.TripInformationProto.TripInformation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(beam.sim.traveltime.TripInformationProto.TripInformation other) {
        if (other == beam.sim.traveltime.TripInformationProto.TripInformation.getDefaultInstance()) return this;
        if (routeInformationElementsBuilder_ == null) {
          if (!other.routeInformationElements_.isEmpty()) {
            if (routeInformationElements_.isEmpty()) {
              routeInformationElements_ = other.routeInformationElements_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRouteInformationElementsIsMutable();
              routeInformationElements_.addAll(other.routeInformationElements_);
            }
            onChanged();
          }
        } else {
          if (!other.routeInformationElements_.isEmpty()) {
            if (routeInformationElementsBuilder_.isEmpty()) {
              routeInformationElementsBuilder_.dispose();
              routeInformationElementsBuilder_ = null;
              routeInformationElements_ = other.routeInformationElements_;
              bitField0_ = (bitField0_ & ~0x00000001);
              routeInformationElementsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRouteInformationElementsFieldBuilder() : null;
            } else {
              routeInformationElementsBuilder_.addAllMessages(other.routeInformationElements_);
            }
          }
        }
        if (other.hasDepartureTime()) {
          setDepartureTime(other.getDepartureTime());
        }
        if (other.hasTripTravelTime()) {
          setTripTravelTime(other.getTripTravelTime());
        }
        if (other.hasTripTravelDistance()) {
          setTripTravelDistance(other.getTripTravelDistance());
        }
        if (other.hasTripAverageSpeed()) {
          setTripAverageSpeed(other.getTripAverageSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        beam.sim.traveltime.TripInformationProto.TripInformation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (beam.sim.traveltime.TripInformationProto.TripInformation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<beam.sim.traveltime.TripInformationProto.RouteInformationElement> routeInformationElements_ =
        java.util.Collections.emptyList();
      private void ensureRouteInformationElementsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          routeInformationElements_ = new java.util.ArrayList<beam.sim.traveltime.TripInformationProto.RouteInformationElement>(routeInformationElements_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          beam.sim.traveltime.TripInformationProto.RouteInformationElement, beam.sim.traveltime.TripInformationProto.RouteInformationElement.Builder, beam.sim.traveltime.TripInformationProto.RouteInformationElementOrBuilder> routeInformationElementsBuilder_;

      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public java.util.List<beam.sim.traveltime.TripInformationProto.RouteInformationElement> getRouteInformationElementsList() {
        if (routeInformationElementsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(routeInformationElements_);
        } else {
          return routeInformationElementsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public int getRouteInformationElementsCount() {
        if (routeInformationElementsBuilder_ == null) {
          return routeInformationElements_.size();
        } else {
          return routeInformationElementsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public beam.sim.traveltime.TripInformationProto.RouteInformationElement getRouteInformationElements(int index) {
        if (routeInformationElementsBuilder_ == null) {
          return routeInformationElements_.get(index);
        } else {
          return routeInformationElementsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public Builder setRouteInformationElements(
          int index, beam.sim.traveltime.TripInformationProto.RouteInformationElement value) {
        if (routeInformationElementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRouteInformationElementsIsMutable();
          routeInformationElements_.set(index, value);
          onChanged();
        } else {
          routeInformationElementsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public Builder setRouteInformationElements(
          int index, beam.sim.traveltime.TripInformationProto.RouteInformationElement.Builder builderForValue) {
        if (routeInformationElementsBuilder_ == null) {
          ensureRouteInformationElementsIsMutable();
          routeInformationElements_.set(index, builderForValue.build());
          onChanged();
        } else {
          routeInformationElementsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public Builder addRouteInformationElements(beam.sim.traveltime.TripInformationProto.RouteInformationElement value) {
        if (routeInformationElementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRouteInformationElementsIsMutable();
          routeInformationElements_.add(value);
          onChanged();
        } else {
          routeInformationElementsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public Builder addRouteInformationElements(
          int index, beam.sim.traveltime.TripInformationProto.RouteInformationElement value) {
        if (routeInformationElementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRouteInformationElementsIsMutable();
          routeInformationElements_.add(index, value);
          onChanged();
        } else {
          routeInformationElementsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public Builder addRouteInformationElements(
          beam.sim.traveltime.TripInformationProto.RouteInformationElement.Builder builderForValue) {
        if (routeInformationElementsBuilder_ == null) {
          ensureRouteInformationElementsIsMutable();
          routeInformationElements_.add(builderForValue.build());
          onChanged();
        } else {
          routeInformationElementsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public Builder addRouteInformationElements(
          int index, beam.sim.traveltime.TripInformationProto.RouteInformationElement.Builder builderForValue) {
        if (routeInformationElementsBuilder_ == null) {
          ensureRouteInformationElementsIsMutable();
          routeInformationElements_.add(index, builderForValue.build());
          onChanged();
        } else {
          routeInformationElementsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public Builder addAllRouteInformationElements(
          java.lang.Iterable<? extends beam.sim.traveltime.TripInformationProto.RouteInformationElement> values) {
        if (routeInformationElementsBuilder_ == null) {
          ensureRouteInformationElementsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, routeInformationElements_);
          onChanged();
        } else {
          routeInformationElementsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public Builder clearRouteInformationElements() {
        if (routeInformationElementsBuilder_ == null) {
          routeInformationElements_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          routeInformationElementsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public Builder removeRouteInformationElements(int index) {
        if (routeInformationElementsBuilder_ == null) {
          ensureRouteInformationElementsIsMutable();
          routeInformationElements_.remove(index);
          onChanged();
        } else {
          routeInformationElementsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public beam.sim.traveltime.TripInformationProto.RouteInformationElement.Builder getRouteInformationElementsBuilder(
          int index) {
        return getRouteInformationElementsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public beam.sim.traveltime.TripInformationProto.RouteInformationElementOrBuilder getRouteInformationElementsOrBuilder(
          int index) {
        if (routeInformationElementsBuilder_ == null) {
          return routeInformationElements_.get(index);  } else {
          return routeInformationElementsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public java.util.List<? extends beam.sim.traveltime.TripInformationProto.RouteInformationElementOrBuilder> 
           getRouteInformationElementsOrBuilderList() {
        if (routeInformationElementsBuilder_ != null) {
          return routeInformationElementsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(routeInformationElements_);
        }
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public beam.sim.traveltime.TripInformationProto.RouteInformationElement.Builder addRouteInformationElementsBuilder() {
        return getRouteInformationElementsFieldBuilder().addBuilder(
            beam.sim.traveltime.TripInformationProto.RouteInformationElement.getDefaultInstance());
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public beam.sim.traveltime.TripInformationProto.RouteInformationElement.Builder addRouteInformationElementsBuilder(
          int index) {
        return getRouteInformationElementsFieldBuilder().addBuilder(
            index, beam.sim.traveltime.TripInformationProto.RouteInformationElement.getDefaultInstance());
      }
      /**
       * <code>repeated .beam_pevs.RouteInformationElement routeInformationElements = 1;</code>
       */
      public java.util.List<beam.sim.traveltime.TripInformationProto.RouteInformationElement.Builder> 
           getRouteInformationElementsBuilderList() {
        return getRouteInformationElementsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          beam.sim.traveltime.TripInformationProto.RouteInformationElement, beam.sim.traveltime.TripInformationProto.RouteInformationElement.Builder, beam.sim.traveltime.TripInformationProto.RouteInformationElementOrBuilder> 
          getRouteInformationElementsFieldBuilder() {
        if (routeInformationElementsBuilder_ == null) {
          routeInformationElementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              beam.sim.traveltime.TripInformationProto.RouteInformationElement, beam.sim.traveltime.TripInformationProto.RouteInformationElement.Builder, beam.sim.traveltime.TripInformationProto.RouteInformationElementOrBuilder>(
                  routeInformationElements_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          routeInformationElements_ = null;
        }
        return routeInformationElementsBuilder_;
      }

      private double departureTime_ ;
      /**
       * <code>optional double departureTime = 2;</code>
       */
      public boolean hasDepartureTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double departureTime = 2;</code>
       */
      public double getDepartureTime() {
        return departureTime_;
      }
      /**
       * <code>optional double departureTime = 2;</code>
       */
      public Builder setDepartureTime(double value) {
        bitField0_ |= 0x00000002;
        departureTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double departureTime = 2;</code>
       */
      public Builder clearDepartureTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        departureTime_ = 0D;
        onChanged();
        return this;
      }

      private double tripTravelTime_ ;
      /**
       * <code>optional double tripTravelTime = 3;</code>
       */
      public boolean hasTripTravelTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional double tripTravelTime = 3;</code>
       */
      public double getTripTravelTime() {
        return tripTravelTime_;
      }
      /**
       * <code>optional double tripTravelTime = 3;</code>
       */
      public Builder setTripTravelTime(double value) {
        bitField0_ |= 0x00000004;
        tripTravelTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double tripTravelTime = 3;</code>
       */
      public Builder clearTripTravelTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tripTravelTime_ = 0D;
        onChanged();
        return this;
      }

      private double tripTravelDistance_ ;
      /**
       * <code>optional double tripTravelDistance = 4;</code>
       */
      public boolean hasTripTravelDistance() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double tripTravelDistance = 4;</code>
       */
      public double getTripTravelDistance() {
        return tripTravelDistance_;
      }
      /**
       * <code>optional double tripTravelDistance = 4;</code>
       */
      public Builder setTripTravelDistance(double value) {
        bitField0_ |= 0x00000008;
        tripTravelDistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double tripTravelDistance = 4;</code>
       */
      public Builder clearTripTravelDistance() {
        bitField0_ = (bitField0_ & ~0x00000008);
        tripTravelDistance_ = 0D;
        onChanged();
        return this;
      }

      private double tripAverageSpeed_ ;
      /**
       * <code>optional double tripAverageSpeed = 5;</code>
       */
      public boolean hasTripAverageSpeed() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double tripAverageSpeed = 5;</code>
       */
      public double getTripAverageSpeed() {
        return tripAverageSpeed_;
      }
      /**
       * <code>optional double tripAverageSpeed = 5;</code>
       */
      public Builder setTripAverageSpeed(double value) {
        bitField0_ |= 0x00000010;
        tripAverageSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double tripAverageSpeed = 5;</code>
       */
      public Builder clearTripAverageSpeed() {
        bitField0_ = (bitField0_ & ~0x00000010);
        tripAverageSpeed_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:beam_pevs.TripInformation)
    }

    static {
      defaultInstance = new TripInformation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:beam_pevs.TripInformation)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beam_pevs_RouteInformationElement_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_beam_pevs_RouteInformationElement_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_beam_pevs_TripInformation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_beam_pevs_TripInformation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026trip_infromation.proto\022\tbeam_pevs\"U\n\027R" +
      "outeInformationElement\022\022\n\ntravelTime\030\001 \001" +
      "(\001\022\026\n\016travelDistance\030\002 \001(\001\022\016\n\006linkId\030\003 \001" +
      "(\t\"\274\001\n\017TripInformation\022D\n\030routeInformati" +
      "onElements\030\001 \003(\0132\".beam_pevs.RouteInform" +
      "ationElement\022\025\n\rdepartureTime\030\002 \001(\001\022\026\n\016t" +
      "ripTravelTime\030\003 \001(\001\022\032\n\022tripTravelDistanc" +
      "e\030\004 \001(\001\022\030\n\020tripAverageSpeed\030\005 \001(\001B+\n\023bea" +
      "m.sim.traveltimeB\024TripInformationProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_beam_pevs_RouteInformationElement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_beam_pevs_RouteInformationElement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_beam_pevs_RouteInformationElement_descriptor,
        new java.lang.String[] { "TravelTime", "TravelDistance", "LinkId", });
    internal_static_beam_pevs_TripInformation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_beam_pevs_TripInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_beam_pevs_TripInformation_descriptor,
        new java.lang.String[] { "RouteInformationElements", "DepartureTime", "TripTravelTime", "TripTravelDistance", "TripAverageSpeed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
