{
 "title": "Beam Simulation. Iteration view comparison",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "left_run_name",
    "label": "left run name",
    "query": "SHOW TAG VALUES ON \"beam\" FROM \"beam-run\" WITH KEY = \"unique-run-name\""
   },
   {
    "name": "left_iteration_num",
    "label": "left iteration num",
    "query": "SELECT count FROM \"beam\".\"autogen\".\"beam-iteration\" WHERE \"unique-run-name\" = '$left_run_name'"
   },
   {
    "name": "right_run_name",
    "label": "right run name",
    "query": "SHOW TAG VALUES ON \"beam\" FROM \"beam-run\" WITH KEY = \"unique-run-name\""
   },
   {
    "name": "right_iteration_num",
    "label": "right iteration num",
    "query": "SELECT count FROM \"beam\".\"autogen\".\"beam-iteration\" WHERE \"unique-run-name\" = '$right_run_name'"
   }
  ]
 },
 "panels": [
  {
   "title": "BEV non CAV Distance \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "bev-no-cav-distance",
     "query": "SELECT sum(\"count\") FROM \"bev-no-cav-distance\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "BEV non CAV Distance \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "bev-no-cav-distance",
     "query": "SELECT sum(\"count\") FROM \"bev-no-cav-distance\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$right_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "BEV non CAV Vehicles \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "bev-no-cav-time",
     "query": "SELECT sum(\"count\") FROM \"bev-no-cav-time\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "BEV non CAV Vehicles \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "bev-no-cav-time",
     "query": "SELECT sum(\"count\") FROM \"bev-no-cav-time\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$right_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "BEV CAV Distance \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "bev-cav-distance",
     "query": "SELECT sum(\"count\") FROM \"bev-cav-distance\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "BEV CAV Distance \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "bev-cav-distance",
     "query": "SELECT sum(\"count\") FROM \"bev-cav-distance\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$right_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "BEV CAV Vehicles \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "bev-cav-time",
     "query": "SELECT sum(\"count\") FROM \"bev-cav-time\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "BEV CAV Vehicles \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "bev-cav-time",
     "query": "SELECT sum(\"count\") FROM \"bev-cav-time\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$right_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "RH non CAV Distance \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-no-cav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-no-cav-distance\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "RH non CAV Distance \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-no-cav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-no-cav-distance\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$right_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "RH non CAV Vehicles \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-no-cav-time",
     "query": "SELECT sum(\"count\") FROM \"rh-no-cav-time\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "RH non CAV Vehicles \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-no-cav-time",
     "query": "SELECT sum(\"count\") FROM \"rh-no-cav-time\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$right_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "RH CAV Distance \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-cav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-cav-distance\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "RH CAV Distance \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-cav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-cav-distance\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$right_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "RH CAV Vehicles \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-cav-time",
     "query": "SELECT sum(\"count\") FROM \"rh-cav-time\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "RH CAV Vehicles \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-cav-time",
     "query": "SELECT sum(\"count\") FROM \"rh-cav-time\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$right_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Power Average Load by Parking Type \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "alias": "[[tag_parkingType]]",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "parkingType" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"averageLoad\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"simulation-hour\", \"parkingType\"",
     "select": [
      [
       { "params": [ "averageLoad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Power Average Load by Parking Type \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "alias": "[[tag_parkingType]]",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "parkingType" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"averageLoad\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/)  GROUP BY \"simulation-hour\", \"parkingType\"",
     "select": [
      [
       { "params": [ "averageLoad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Power Average Load by Charger Type \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "alias": "[[tag_typeOfCharger]]",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "chargerType" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"averageLoad\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"simulation-hour\", \"typeOfCharger\"",
     "select": [
      [
       { "params": [ "averageLoad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Power Average Load by Charger Type \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "alias": "[[tag_typeOfCharger]]",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "chargerType" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"averageLoad\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/)  GROUP BY \"simulation-hour\", \"typeOfCharger\"",
     "select": [
      [
       { "params": [ "averageLoad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Power Average Load by User Type \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "alias": "[[tag_vehicleType]]",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "vehicleType" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"averageLoad\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"simulation-hour\", \"vehicleType\"",
     "select": [
      [
       { "params": [ "averageLoad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Power Average Load by User Type \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "alias": "[[tag_vehicleType]]",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "vehicleType" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"averageLoad\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/)  GROUP BY \"simulation-hour\", \"vehicleType\"",
     "select": [
      [
       { "params": [ "averageLoad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Trip Distance for Ride Hail \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "alias": "[[tag_trip-type]]",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "trip-type" ], "type": "tag" }
     ],
     "measurement": "ride-hail-trip-distance",
     "query": "SELECT sum(\"count\") FROM \"ride-hail-trip-distance\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"simulation-hour\", \"trip-type\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Trip Distance for Ride Hail \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "alias": "[[tag_trip-type]]",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "trip-type" ], "type": "tag" }
     ],
     "measurement": "ride-hail-trip-distance",
     "query": "SELECT sum(\"count\") FROM \"ride-hail-trip-distance\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/)  GROUP BY \"simulation-hour\", \"trip-type\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Mode Choice \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "alias": "$tag_mode",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "mode" ], "type": "tag" }
     ],
     "measurement": "mode-choices",
     "query": "SELECT sum(\"count\") FROM \"mode-choices\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"simulation-hour\", \"mode\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Mode Choice \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "alias": "$tag_mode",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "mode" ], "type": "tag" }
     ],
     "measurement": "mode-choices",
     "query": "SELECT sum(\"count\") FROM \"mode-choices\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/)  GROUP BY \"simulation-hour\", \"mode\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Parking \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "alias": "Parking $tag_parking-type",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "parking-type" ], "type": "tag" }
     ],
     "measurement": "parking",
     "query": "SELECT sum(\"count\") FROM \"parking\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"simulation-hour\", \"parking-type\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Parking \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "alias": "Parking $tag_parking-type",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "parking-type" ], "type": "tag" }
     ],
     "measurement": "parking",
     "query": "SELECT sum(\"count\") FROM \"parking\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/)  GROUP BY \"simulation-hour\", \"parking-type\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Ride Hail Allocation Reserved \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "targets": [
    {
     "alias": "Allocation reserved",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "mode" ], "type": "tag" }
     ],
     "measurement": "ride-hail-allocation-reserved",
     "query": "SELECT sum(\"count\") FROM \"ride-hail-allocation-reserved\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"simulation-hour\", \"mode\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Ride Hail Allocation Reserved \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "targets": [
    {
     "alias": "Allocation reserved",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "mode" ], "type": "tag" }
     ],
     "measurement": "ride-hail-allocation-reserved",
     "query": "SELECT sum(\"count\") FROM \"ride-hail-allocation-reserved\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/)  GROUP BY \"simulation-hour\", \"mode\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Ride Hail Inquiry Served \"$left_run_name\" it $left_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "targets": [
    {
     "alias": "Inquiry served",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "iteration-num" ], "type": "tag" }
     ],
     "measurement": "ride-hail-inquiry-served",
     "query": "SELECT sum(\"count\") FROM \"ride-hail-inquiry-served\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/ AND \"iteration-num\" =~ /^$left_iteration_num$/) GROUP BY \"simulation-hour\", \"iteration-num\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Ride Hail Inquiry Served \"$right_run_name\" it $right_iteration_num",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
   "targets": [
    {
     "alias": "Inquiry served",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "iteration-num" ], "type": "tag" }
     ],
     "measurement": "ride-hail-inquiry-served",
     "query": "SELECT sum(\"count\") FROM \"ride-hail-inquiry-served\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/ AND \"iteration-num\" =~ /^$right_iteration_num$/)  GROUP BY \"simulation-hour\", \"iteration-num\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$left_iteration_num$/" }
     ]
    }
   ]
  }
 ]
}