{
 "title": "Beam Simulation. Global view",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "run_name",
    "label": "run_name",
    "query": "SHOW TAG VALUES ON \"beam\" FROM \"beam-run\" WITH KEY = \"unique-run-name\""
   }
  ]
 },
 "panels": [
  {
   "title": "BEV non CAV Distance",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "BEV_NO_CAV_DISTANCE",
     "query": "SELECT sum(\"count\") FROM \"BEV_NO_CAV_DISTANCE\" WHERE (\"unique-run-name\" =~ /^$run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "BEV non CAV Time",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "BEV_NO_CAV_DISTANCE",
     "query": "SELECT sum(\"count\") FROM \"BEV_NO_CAV_TIME\" WHERE (\"unique-run-name\" =~ /^$run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charge Events by Charger Type",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "typeOfCharger" ], "type": "tag" },
      { "params": [ "iteration-num" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"count\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$run_name$/) GROUP BY \"typeOfCharger\", \"iteration-num\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charge Events by Parking Type",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "parkingType" ], "type": "tag" },
      { "params": [ "iteration-num" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"count\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$run_name$/) GROUP BY \"parkingType\", \"iteration-num\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Trip Distance [Ride Hail]",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "trip-type" ], "type": "tag" }
     ],
     "measurement": "ride-hail-trip-distance",
     "query": "SELECT sum(\"count\") FROM \"ride-hail-trip-distance\" WHERE (\"unique-run-name\" =~ /^$run_name$/) GROUP BY \"iteration-num\", \"trip-type\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Mode Choice",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "iteration-num" ], "type": "tag" }
     ],
     "measurement": "mode-choices",
     "query": "SELECT sum(\"count\") FROM \"mode-choices\" WHERE (\"unique-run-name\" =~ /^$run_name$/) GROUP BY \"mode\", \"iteration-num\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Travel Time [Car]",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "mode" ], "type": "tag" }
     ],
     "measurement": "average-travel-time",
     "query": "SELECT \"count\" FROM \"average-travel-time\" WHERE (\"unique-run-name\" =~ /^$run_name$/) GROUP BY \"iteration-num\", \"mode\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  }
 ]
}