{
 "title": "Beam Simulation. Iteration view",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "run_name",
    "label": "run name",
    "query": "SHOW TAG VALUES ON \"beam\" FROM \"beam-run\" WITH KEY = \"unique-run-name\""
   },
   {
    "name": "iteration_num",
    "label": "iteration num",
    "query": "SELECT count FROM \"beam\".\"autogen\".\"beam-iteration\" WHERE \"unique-run-name\" = '$run_name'"
   }
  ]
 },
 "panels": [
  {
   "title": "Households",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-households",
     "query": "SELECT \"count\" FROM \"beam-run-households\" WHERE (\"unique-run-name\" =~ /^$run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Population",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-population-size",
     "query": "SELECT \"count\" FROM \"beam-run-population-size\" WHERE (\"unique-run-name\" =~ /^$run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Private Fleet",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-private-fleet-size",
     "query": "SELECT \"count\" FROM \"beam-run-private-fleet-size\" WHERE (\"unique-run-name\" =~ /^$run_name$/) ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Depots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-charging-depots-cnt",
     "query": "SELECT \"count\" FROM \"beam-run-charging-depots-cnt\" WHERE (\"unique-run-name\" =~ /^$run_name$/) ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Public Fast Charge",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-public-fast-charge-cnt",
     "query": "SELECT \"count\" FROM \"beam-run-public-fast-charge-cnt\" WHERE (\"unique-run-name\" =~ /^$run_name$/) ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "RH EV non CAV",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-RH-ev-non-cav",
     "query": "SELECT \"count\" FROM \"beam-run-RH-ev-non-cav\" WHERE (\"unique-run-name\" =~ /^$run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "RH EV CAV",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-RH-ev-cav",
     "query": "SELECT \"count\" FROM \"beam-run-RH-ev-cav\" WHERE (\"unique-run-name\" =~ /^$run_name$/) ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "RH non EV non CAV",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-RH-non-ev-non-cav",
     "query": "SELECT \"count\" FROM \"beam-run-RH-non-ev-non-cav\" WHERE (\"unique-run-name\" =~ /^$run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "RH non EV CAV",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-RH-non-ev-cav",
     "query": "SELECT \"count\" FROM \"beam-run-RH-non-ev-cav\" WHERE (\"unique-run-name\" =~ /^$run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Depots Stalls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-charging-depots-stalls-cnt",
     "query": "SELECT \"count\" FROM \"beam-run-charging-depots-stalls-cnt\" WHERE (\"unique-run-name\" =~ /^$run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Public Fast Charge Stalls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-public-fast-charge-stalls-cnt",
     "query": "SELECT \"count\" FROM \"beam-run-public-fast-charge-stalls-cnt\" WHERE (\"unique-run-name\" =~ /^$run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "EV non CAV Ridehail Distance",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-ev-nocav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-ev-nocav-distance\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "EV non CAV Ridehail Count",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-ev-nocav-count",
     "query": "SELECT sum(\"count\") FROM \"rh-ev-nocav-count\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "EV CAV Ridehail Distance",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-ev-cav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-ev-cav-distance\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "EV CAV Ridehail Count",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-ev-cav-count",
     "query": "SELECT sum(\"count\") FROM \"rh-ev-cav-count\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Non EV non CAV Ridehail Distance",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-noev-nocav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-noev-nocav-distance\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Non EV non CAV Ridehail Count",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-noev-nocav-count",
     "query": "SELECT sum(\"count\") FROM \"rh-noev-nocav-count\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Non EV CAV Ridehail Distance",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-noev-cav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-noev-cav-distance\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Non EV CAV Ridehail Count",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vehicle-state" ], "type": "tag" },
      { "params": [ "simulation-hour" ], "type": "tag" }
     ],
     "measurement": "rh-noev-cav-count",
     "query": "SELECT sum(\"count\") FROM \"rh-noev-cav-count\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"vehicle-state\", \"simulation-hour\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Power Average Load by Parking Type",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "alias": "[[tag_parkingType]]",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "parkingType" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"averageLoad\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"simulation-hour\", \"parkingType\"",
     "select": [
      [
       { "params": [ "averageLoad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Power Average Load by Charger Type",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "alias": "[[tag_typeOfCharger]]",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "chargerType" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"averageLoad\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"simulation-hour\", \"typeOfCharger\"",
     "select": [
      [
       { "params": [ "averageLoad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Power Average Load by User Type",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "alias": "[[tag_vehicleType]]",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "vehicleType" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"averageLoad\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"simulation-hour\", \"vehicleType\"",
     "select": [
      [
       { "params": [ "averageLoad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Trip Distance for Ride Hail",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "alias": "[[tag_trip-type]]",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "trip-type" ], "type": "tag" }
     ],
     "measurement": "ride-hail-trip-distance",
     "query": "SELECT sum(\"count\") FROM \"ride-hail-trip-distance\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"simulation-hour\", \"trip-type\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Mode Choice",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "alias": "$tag_mode",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "mode" ], "type": "tag" }
     ],
     "measurement": "mode-choices",
     "query": "SELECT sum(\"count\") FROM \"mode-choices\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"simulation-hour\", \"mode\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Ride Hail Waiting Histogram",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "alias": "[[tag_trip-type]]",
     "groupBy": [
      { "params": [ "simulation-hour" ], "type": "tag" },
      { "params": [ "category" ], "type": "tag" }
     ],
     "measurement": "ride-hail-waiting-time",
     "query": "SELECT \"count\" FROM \"ride-hail-waiting-time\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"simulation-hour\", \"category\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  },
  {
   "title": "Parking",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "alias": "Parking $tag_parking-type",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "parking-type" ], "type": "tag" }
     ],
     "measurement": "parking",
     "query": "SELECT sum(\"count\") FROM \"parking\" WHERE (\"unique-run-name\" =~ /^$run_name$/ AND \"iteration-num\" =~ /^$iteration_num$/) GROUP BY \"simulation-hour\", \"parking-type\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$run_name$/" },
      { "condition": "AND", "key": "iteration-num", "operator": "=~", "value": "/^$iteration_num$/" }
     ]
    }
   ]
  }
 ]
}