{
 "title": "Beam Simulation. Global view comparison",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "left_run_name",
    "label": "left run name",
    "query": "SHOW TAG VALUES ON \"beam\" FROM \"beam-run\" WITH KEY = \"unique-run-name\""
   },
   {
    "name": "right_run_name",
    "label": "right run name",
    "query": "SHOW TAG VALUES ON \"beam\" FROM \"beam-run\" WITH KEY = \"unique-run-name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Households",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-households",
     "query": "SELECT \"count\" FROM \"beam-run-households\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Population",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-population-size",
     "query": "SELECT \"count\" FROM \"beam-run-population-size\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Private Fleet",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-private-fleet-size",
     "query": "SELECT \"count\" FROM \"beam-run-private-fleet-size\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Households",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-households",
     "query": "SELECT \"count\" FROM \"beam-run-households\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Population",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-population-size",
     "query": "SELECT \"count\" FROM \"beam-run-population-size\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Private Fleet",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-private-fleet-size",
     "query": "SELECT \"count\" FROM \"beam-run-private-fleet-size\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "RH EV non CAV",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-RH-ev-non-cav",
     "query": "SELECT \"count\" FROM \"beam-run-RH-ev-non-cav\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "RH EV CAV",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-RH-ev-cav",
     "query": "SELECT \"count\" FROM \"beam-run-RH-ev-cav\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "RH non EV non CAV",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-RH-non-ev-non-cav",
     "query": "SELECT \"count\" FROM \"beam-run-RH-non-ev-non-cav\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "RH non EV CAV",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-RH-non-ev-cav",
     "query": "SELECT \"count\" FROM \"beam-run-RH-non-ev-cav\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "RH EV non CAV",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-RH-ev-non-cav",
     "query": "SELECT \"count\" FROM \"beam-run-RH-ev-non-cav\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "RH EV CAV",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-RH-ev-cav",
     "query": "SELECT \"count\" FROM \"beam-run-RH-ev-cav\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "RH non EV non CAV",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-RH-non-ev-non-cav",
     "query": "SELECT \"count\" FROM \"beam-run-RH-non-ev-non-cav\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "RH non EV CAV",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-RH-non-ev-cav",
     "query": "SELECT \"count\" FROM \"beam-run-RH-non-ev-cav\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Depots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-charging-depots-cnt",
     "query": "SELECT \"count\" FROM \"beam-run-charging-depots-cnt\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Depots Stalls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-charging-depots-stalls-cnt",
     "query": "SELECT \"count\" FROM \"beam-run-charging-depots-stalls-cnt\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Public Fast Charge",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-public-fast-charge-cnt",
     "query": "SELECT \"count\" FROM \"beam-run-public-fast-charge-cnt\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Public Fast Charge Stalls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-public-fast-charge-stalls-cnt",
     "query": "SELECT \"count\" FROM \"beam-run-public-fast-charge-stalls-cnt\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Depots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-charging-depots-cnt",
     "query": "SELECT \"count\" FROM \"beam-run-charging-depots-cnt\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charging Depots Stalls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-charging-depots-stalls-cnt",
     "query": "SELECT \"count\" FROM \"beam-run-charging-depots-stalls-cnt\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Public Fast Charge",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-public-fast-charge-cnt",
     "query": "SELECT \"count\" FROM \"beam-run-public-fast-charge-cnt\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Public Fast Charge Stalls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "beam-run-public-fast-charge-stalls-cnt",
     "query": "SELECT \"count\" FROM \"beam-run-public-fast-charge-stalls-cnt\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "EV non CAV Ridehail Distance per Iteration \"$left_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-ev-nocav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-ev-nocav-distance\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "EV non CAV Ridehail Distance per Iteration \"$right_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-ev-nocav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-ev-nocav-distance\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "EV non CAV Ridehail Count per Iteration \"$left_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-ev-nocav-count",
     "query": "SELECT sum(\"count\") FROM \"rh-ev-nocav-count\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "EV non CAV Ridehail Count per Iteration \"$right_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-ev-nocav-count",
     "query": "SELECT sum(\"count\") FROM \"rh-ev-nocav-count\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "EV CAV Ridehail Distance per Iteration \"$left_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-ev-cav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-ev-cav-distance\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "EV CAV Ridehail Distance per Iteration \"$right_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-ev-cav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-ev-cav-distance\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "EV CAV Ridehail Count per Iteration \"$left_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-ev-cav-count",
     "query": "SELECT sum(\"count\") FROM \"rh-ev-cav-count\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "EV CAV Ridehail Count per Iteration \"$right_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-ev-cav-count",
     "query": "SELECT sum(\"count\") FROM \"rh-ev-cav-count\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Non EV non CAV Ridehail Distance per Iteration \"$left_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-noev-nocav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-noev-nocav-distance\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Non EV non CAV Ridehail Distance per Iteration \"$right_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-noev-nocav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-noev-nocav-distance\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Non EV non CAV Ridehail Count per Iteration \"$left_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-noev-nocav-count",
     "query": "SELECT sum(\"count\") FROM \"rh-noev-nocav-count\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Non EV non CAV Ridehail Count per Iteration \"$right_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-noev-nocav-count",
     "query": "SELECT sum(\"count\") FROM \"rh-noev-nocav-count\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Non EV CAV Ridehail Distance per Iteration \"$left_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-noev-cav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-noev-cav-distance\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Non EV CAV Ridehail Distance per Iteration \"$right_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-noev-cav-distance",
     "query": "SELECT sum(\"count\") FROM \"rh-noev-cav-distance\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Non EV CAV Ridehail Count per Iteration \"$left_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-noev-cav-count",
     "query": "SELECT sum(\"count\") FROM \"rh-noev-cav-count\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Non EV CAV Ridehail Count per Iteration \"$right_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "vehicle-state" ], "type": "tag" }
     ],
     "measurement": "rh-noev-cav-count",
     "query": "SELECT sum(\"count\") FROM \"rh-noev-cav-count\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) GROUP BY \"iteration-num\", \"vehicle-state\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$right_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charge Events by Charger Type \"$left_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "typeOfCharger" ], "type": "tag" },
      { "params": [ "iteration-num" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"count\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/) GROUP BY \"typeOfCharger\", \"iteration-num\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charge Events by Charger Type \"$right_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "typeOfCharger" ], "type": "tag" },
      { "params": [ "iteration-num" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"count\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) GROUP BY \"typeOfCharger\", \"iteration-num\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charge Events by Parking Type \"$left_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "parkingType" ], "type": "tag" },
      { "params": [ "iteration-num" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"count\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/) GROUP BY \"parkingType\", \"iteration-num\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charge Events by Parking Type \"$right_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "parkingType" ], "type": "tag" },
      { "params": [ "iteration-num" ], "type": "tag" }
     ],
     "measurement": "chargingPower",
     "query": "SELECT sum(\"count\") FROM \"chargingPower\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) GROUP BY \"parkingType\", \"iteration-num\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Trip Distance for Ride Hail \"$left_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "trip-type" ], "type": "tag" }
     ],
     "measurement": "ride-hail-trip-distance",
     "query": "SELECT sum(\"count\") FROM \"ride-hail-trip-distance\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/) GROUP BY \"iteration-num\", \"trip-type\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Trip Distance for Ride Hail \"$right_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "trip-type" ], "type": "tag" }
     ],
     "measurement": "ride-hail-trip-distance",
     "query": "SELECT sum(\"count\") FROM \"ride-hail-trip-distance\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) GROUP BY \"iteration-num\", \"trip-type\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Mode Choice \"$left_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "iteration-num" ], "type": "tag" }
     ],
     "measurement": "mode-choices",
     "query": "SELECT sum(\"count\") FROM \"mode-choices\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/) GROUP BY \"mode\", \"iteration-num\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Mode Choice \"$right_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "iteration-num" ], "type": "tag" }
     ],
     "measurement": "mode-choices",
     "query": "SELECT sum(\"count\") FROM \"mode-choices\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) GROUP BY \"mode\", \"iteration-num\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Travel Time for Car \"$left_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "mode" ], "type": "tag" }
     ],
     "measurement": "average-travel-time",
     "query": "SELECT sum(\"count\") FROM \"average-travel-time\" WHERE (\"unique-run-name\" =~ /^$left_run_name$/) GROUP BY \"iteration-num\", \"mode\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Travel Time for Car \"$right_run_name\"",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "iteration-num" ], "type": "tag" },
      { "params": [ "mode" ], "type": "tag" }
     ],
     "measurement": "average-travel-time",
     "query": "SELECT sum(\"count\") FROM \"average-travel-time\" WHERE (\"unique-run-name\" =~ /^$right_run_name$/) GROUP BY \"iteration-num\", \"mode\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "unique-run-name", "operator": "=~", "value": "/^$left_run_name$/" }
     ]
    }
   ]
  }
 ]
}