AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  s3BucketList:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::340032650202:role/BeamLambdaExecution'
      Environment:
        Variables:
          IAM_INSTANACE_PROFILE: BeamCodeDeployEC2
          IMAGE_ID: ami-05f09f7d7fced8241
          INSTANCE_TYPE: t2.small
          KEY: beam-box
          SECURITY_GROUP: sg-f0412698
