AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: BEAM Sim
Resources:
  simulateBeam:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: BEAM Sim
      MemorySize: 128
      Timeout: 59
      Role: 'arn:aws:iam::340032650202:role/BeamLambdaExecution'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /ec2StartStop
            Method: ANY
      Environment:
        Variables:
          SHUTDOWN_BEHAVIOUR: terminate
