@startuml
scale 700 width
[*] --> Uninitialized

state Uninitialized

state InActivity{
    state PerformingActivity
}

state Deciding{
    state ChoosingMode
}


state Traveling{

    state InVehicle{
        state DrivingCar
        state RidingPT
    }

    state Walking

}

state Stopped



PerformingActivity --> Deciding: ActivityEndTrigger



Uninitialized --> Initialized: Initialize

Initialized  --> PerformingActivity: ActivityStartTrigger


ChoosingMode --> DrivingCar: PersonDepartureTrigger

ChoosingMode --> Walking: PersonDepartureTrigger

ChoosingMode --> RidingPT: PersonDepartureTrigger


InActivity --> Stopped: IterationEnd

Traveling --> InActivity: ActivityStartTrigger

InActivity --> PerformingActivity


Traveling --> Error: BeamAgentError

InActivity --> Error: BeamAgentError

Deciding --> [*]

Error --> [*]

Stopped --> [*]

@enduml