AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: BEAM Sim
Resources:
  simulateBeam:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: BEAM Sim
      MemorySize: 128
      Timeout: 59
      Role: 'arn:aws:iam::340032650202:role/BeamLambdaExecution'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /simulateBeam
            Method: ANY
      Environment:
        Variables:
          IAM_ROLE: BeamCodeDeployEC2
          INSTANCE_TYPE: t2.small
          us_west_2_KEY_NAME: beambox-oregon
          us_east_2_IMAGE_ID: ami-0dc1f368
          us_east_2_SECURITY_GROUP: sg-bb469dd3
          SHUTDOWN_BEHAVIOUR: terminate
          REGION: us-east-2
          us_east_2_KEY_NAME: beam-box
          us_west_2_IMAGE_ID: ami-a044f4d8
          us_west_2_SECURITY_GROUP: sg-017c717d
