package beam.agentsim.infrastructure

object Parking {

  val PARKING_INFRASTRUCTURE_MANAGER = "PARKING_INFRASTRUCTURE_MANAGER"
  val STREET_PARKING_CAPACITY = "STREET_PARKING_CAPACITY"
  val STREET_PARKING_HOURLY_RATE = "STREET_PARKING_HOURLY_RATE"
  val OFF_STREET_PARKING_CAPACITY = "OFF_STREET_PARKING_CAPACITY"
  val OFF_STREET_PARKING_HOURLY_RATE = "OFF_STREET_PARKING_HOURLY_RATE"
  val PARKING_WITH_CHARGING_L2_CAPACITY = "PARKING_WITH_CHARGING_L2_CAPACITY"
  val PARKING_WITH_CHARGING_L2_HOURLY_RATE = "PARKING_WITH_CHARGING_L2_HOURLY_RATE"
  val PARKING_WITH_CHARGING_L3_CAPACITY = "PARKING_WITH_CHARGING_L2_CAPACITY"
  val PARKING_WITH_CHARGING_L3_HOURLY_RATE = "PARKING_WITH_CHARGING_L2_HOURLY_RATE"

}
