AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: BEAM Spreadsheet content
Resources:
  simulateBeam:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: BEAM Spreadsheet content
      MemorySize: 128
      Timeout: 59
      Role: 'arn:aws:iam::340032650202:role/BeamLambdaExecution'
      Environment:
        Variables:
          REGION: us-east-2