AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An Amazon S3 trigger that retrieves bucket size.
Resources:
  s3BucketHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: An Amazon S3 trigger that retrieves bucket size.
      MemorySize: 128
      Timeout: 899
      Role: 'arn:aws:iam::340032650202:role/BeamLambdaExecution'
      Environment:
        Variables:
          IAM_INSTANACE_PROFILE: BeamCodeDeployEC2
          IMAGE_ID: ami-05f09f7d7fced8241
          INSTANCE_TYPE: t2.small
          KEY: beam-box
          SECURITY_GROUP: sg-f0412698
      Tags:
        'lambda-console:blueprint': s3-get-object-python
