@startuml
...tick = 0...
"scheduler" -> "Person": InitializeTrigger
rnote over "Person": Initialized
"Person" -> "scheduler": CompletionNotice
"scheduler" -> "Person": ActivityStartTrigger
rnote over "Person": PerformingActivity
"Person" -> "scheduler": CompletionNotice
...tick = 24840...
"scheduler" -> "Person": ActivityEndTrigger
rnote over "Person": ChoosingMode
"Person" -> "HouseholdFleetManager:Car": MobilityStatusInquiry
"Person" -> "HouseholdFleetManager:Bike": MobilityStatusInquiry
"Person" -> "bay_wheels": MobilityStatusInquiry
"HouseholdFleetManager:Car" -> "Person": MobilityStatusResponse
"HouseholdFleetManager:Bike" -> "Person": MobilityStatusResponse
"bay_wheels" -> "Person": MobilityStatusResponse
"Person" -> "Person": MobilityStatusResponse
"Person" -> "router": RoutingRequest
"Person" -> "router": RoutingRequest
"Person" -> "RideHailManager": RideHailRequest
"RideHailManager" -> "router": RoutingRequest
"RideHailManager" -> "router": RoutingRequest
"router" -> "Person": RoutingResponse
"router" -> "RideHailManager": RoutingResponse
"router" -> "RideHailManager": RoutingResponse
"RideHailManager" -> "RideHailManager": RoutingResponses
"RideHailManager" -> "Person": RideHailResponse
"Person" -> "ParkingNetworkManager": ParkingInquiry
"router" -> "Person": RoutingResponse
"ParkingNetworkManager" -> "Person": ParkingInquiryResponse
rnote over "Person": FinishingModeChoice
"Person" -> "HouseholdFleetManager:Car": ReleaseVehicle
"Person" -> "scheduler": CompletionNotice
"Person" -> "Person": StateTimeout
rnote over "Person": WaitingForDeparture
"scheduler" -> "Person": PersonDepartureTrigger
rnote over "Person": ProcessingNextLegOrStartActivity
"Person" -> "Person": StateTimeout
rnote over "Person": WaitingToDrive
"Person" -> "scheduler": CompletionNotice
"scheduler" -> "Person": StartLegTrigger
rnote over "Person": Driving
"Person" -> "scheduler": CompletionNotice
"scheduler" -> "Person": EndLegTrigger
rnote over "Person": DrivingInterrupted
"Person" -> "Person": LastLegPassengerSchedule
rnote over "Person": PassengerScheduleEmpty
"Person" -> "Person": PassengerScheduleEmptyMessage
rnote over "Person": ProcessingNextLegOrStartActivity
"Person" -> "Person": StateTimeout
rnote over "Person": WaitingToDrive
"Person" -> "scheduler": CompletionNotice
"scheduler" -> "Person": StartLegTrigger
rnote over "Person": Driving
"Person" -> "scheduler": CompletionNotice
...tick = 24950...
"scheduler" -> "Person": EndLegTrigger
rnote over "Person": DrivingInterrupted
"Person" -> "Person": LastLegPassengerSchedule
rnote over "Person": PassengerScheduleEmpty
"Person" -> "Person": PassengerScheduleEmptyMessage
rnote over "Person": ProcessingNextLegOrStartActivity
"Person" -> "HouseholdFleetManager:Bike": NotifyVehicleIdle
"Person" -> "Person": StateTimeout
rnote over "Person": WaitingToDrive
"Person" -> "scheduler": CompletionNotice
"scheduler" -> "Person": StartLegTrigger
rnote over "Person": Driving
"Person" -> "scheduler": CompletionNotice
"scheduler" -> "Person": EndLegTrigger
rnote over "Person": DrivingInterrupted
"Person" -> "Person": LastLegPassengerSchedule
rnote over "Person": PassengerScheduleEmpty
"Person" -> "Person": PassengerScheduleEmptyMessage
rnote over "Person": ProcessingNextLegOrStartActivity
"Person" -> "Person": NotifyVehicleIdle
"Person" -> "Person": StateTimeout
rnote over "Person": PerformingActivity
"Person" -> "scheduler": CompletionNotice
...tick = 78060...
"scheduler" -> "Person": ActivityEndTrigger
rnote over "Person": ChoosingMode
"Person" -> "router": RoutingRequest
"Person" -> "Person": MobilityStatusResponse
"router" -> "Person": RoutingResponse
rnote over "Person": FinishingModeChoice
"Person" -> "Person": StateTimeout
rnote over "Person": WaitingForDeparture
"Person" -> "scheduler": CompletionNotice
"scheduler" -> "Person": PersonDepartureTrigger
rnote over "Person": ProcessingNextLegOrStartActivity
"Person" -> "Person": StateTimeout
rnote over "Person": WaitingToDrive
"Person" -> "scheduler": CompletionNotice
"scheduler" -> "Person": StartLegTrigger
rnote over "Person": Driving
"Person" -> "scheduler": CompletionNotice
"scheduler" -> "Person": EndLegTrigger
rnote over "Person": DrivingInterrupted
"Person" -> "Person": LastLegPassengerSchedule
rnote over "Person": PassengerScheduleEmpty
"Person" -> "Person": PassengerScheduleEmptyMessage
rnote over "Person": ProcessingNextLegOrStartActivity
"Person" -> "Person": StateTimeout
rnote over "Person": WaitingToDrive
"Person" -> "scheduler": CompletionNotice
"scheduler" -> "Person": StartLegTrigger
rnote over "Person": Driving
"Person" -> "scheduler": CompletionNotice
...tick = 78176...
"scheduler" -> "Person": EndLegTrigger
rnote over "Person": DrivingInterrupted
"Person" -> "Person": LastLegPassengerSchedule
rnote over "Person": PassengerScheduleEmpty
"Person" -> "Person": PassengerScheduleEmptyMessage
rnote over "Person": ProcessingNextLegOrStartActivity
"Person" -> "HouseholdFleetManager:Bike": NotifyVehicleIdle
"Person" -> "Person": StateTimeout
rnote over "Person": WaitingToDrive
"Person" -> "scheduler": CompletionNotice
"scheduler" -> "Person": StartLegTrigger
rnote over "Person": Driving
"Person" -> "scheduler": CompletionNotice
"scheduler" -> "Person": EndLegTrigger
rnote over "Person": DrivingInterrupted
"Person" -> "Person": LastLegPassengerSchedule
rnote over "Person": PassengerScheduleEmpty
"Person" -> "Person": PassengerScheduleEmptyMessage
rnote over "Person": ProcessingNextLegOrStartActivity
"Person" -> "Person": NotifyVehicleIdle
"Person" -> "Person": StateTimeout
rnote over "Person": PerformingActivity
"Person" -> "HouseholdFleetManager:Bike": ReleaseVehicle
"Person" -> "scheduler": CompletionNotice
...tick = 78776...
"scheduler" -> "Person": ActivityEndTrigger
"Person" -> "scheduler": CompletionNotice
"Household" -> "Person": Finish
"Person" -> "Household": Terminated
@enduml
