@startuml
state "WaitingForDeparture" as WaitingForDeparture
state "ProcessingNextLegOrStartActivity" as ProcessingNextLegOrStartActivity
state "Uninitialized" as Uninitialized
state "PerformingActivity" as PerformingActivity
state "ChoosingMode" as ChoosingMode
state "WaitingToDrive" as WaitingToDrive
state "ReleasingParkingSpot" as ReleasingParkingSpot
state "ReadyToChooseParking" as ReadyToChooseParking
state "TryingToBoardVehicle" as TryingToBoardVehicle
state "Waiting" as Waiting
state "ConnectingToChargingPoint" as ConnectingToChargingPoint
state "DrivingInterrupted" as DrivingInterrupted
state "Initialized" as Initialized
state "WaitingForReservationConfirmation" as WaitingForReservationConfirmation
state "FinishingModeChoice" as FinishingModeChoice
state "ReleasingChargingPoint" as ReleasingChargingPoint
state "PassengerScheduleEmpty" as PassengerScheduleEmpty
state "Moving" as Moving
state "Driving" as Driving
state "ChoosingParkingSpot" as ChoosingParkingSpot
ProcessingNextLegOrStartActivity --> WaitingForReservationConfirmation: (111)
Waiting --> Moving: (111)
ReadyToChooseParking --> ChoosingParkingSpot: (2907)
Driving --> DrivingInterrupted: (14393)
ReleasingParkingSpot --> ReleasingChargingPoint: (13)
ProcessingNextLegOrStartActivity --> TryingToBoardVehicle: (512)
PerformingActivity --> ChoosingMode: (4975)
ReleasingParkingSpot --> WaitingToDrive: (2434)
Moving --> ProcessingNextLegOrStartActivity: (111)
Driving --> ConnectingToChargingPoint: (449)
ProcessingNextLegOrStartActivity --> WaitingToDrive: (12395)
FinishingModeChoice --> WaitingForDeparture: (5027)
Driving --> ReadyToChooseParking: (2907)
WaitingForDeparture --> ProcessingNextLegOrStartActivity: (5027)
Initialized --> PerformingActivity: (1988)
ChoosingMode --> FinishingModeChoice: (5027)
ConnectingToChargingPoint --> DrivingInterrupted: (449)
ReleasingChargingPoint --> WaitingToDrive: (13)
ProcessingNextLegOrStartActivity --> PerformingActivity: (4975)
TryingToBoardVehicle --> ProcessingNextLegOrStartActivity: (460)
WaitingForReservationConfirmation --> Waiting: (111)
DrivingInterrupted --> PassengerScheduleEmpty: (14842)
ChoosingParkingSpot --> WaitingToDrive: (2907)
TryingToBoardVehicle --> ChoosingMode: (52)
PassengerScheduleEmpty --> ProcessingNextLegOrStartActivity: (14842)
Uninitialized --> Initialized: (1988)
WaitingToDrive --> Driving: (17749)
ProcessingNextLegOrStartActivity --> ReleasingParkingSpot: (2447)
@enduml
