@startuml

scale 1000 width
scale 800 height
skinparam stateBorderColor #black
skinparam stateFontStyle bold
skinparam arrowColor #black

' BeamAgent: States '
state Uninitialized #grey

state Initialized #grey

state PerformingActivity #eb1921

state WaitingForDeparture #eb1921

state WaitingForReservationConfirmation #eb1921

state Waiting #eb1921

state Moving #eb1921

state PassengerScheduleEmpty #eb1921

state ReadyToChooseParking #eb1921

state TryingToBoardVehicle #eb1921

state ProcessingNextLegOrStartActivity #eb1921

'BeamAgent Transitions'
[*] --> Uninitialized
Uninitialized --> Initialized :InitializeTrigger

Initialized --> PerformingActivity : ActivityStartTrigger


PerformingActivity --> ChoosingMode : ActivityEndTrigger
PerformingActivity --> [*] : ActivityEndTrigger

WaitingForDeparture --> ProcessingNextLegOrStartActivity : PersonDepartureTrigger

WaitingForReservationConfirmation --> Waiting : ReservationResponse
WaitingForReservationConfirmation --> ChoosingMode : ReservationResponse(error)
WaitingForReservationConfirmation --> WaitingForReservationConfirmation : DelayedRideHailResponse
WaitingForReservationConfirmation --> ChoosingMode : RideHailResponseTrigger(error)
WaitingForReservationConfirmation --> Waiting : RideHailResponse
WaitingForReservationConfirmation --> ChoosingMode : RideHailResponse(error)

Waiting --> Moving : BoardVehicleTrigger

Moving --> ProcessingNextLegOrStartActivity : AlightVehicleTrigger

PassengerScheduleEmpty --> ProcessingNextLegOrStartActivity: PassengerScheduleEmptyMessage

ReadyToChooseParking -[#blue,dotted]-> ChoosingParkingSpot: IntermediateTransitionState

TryingToBoardVehicle --> ProcessingNextLegOrStartActivity : Boarded
TryingToBoardVehicle --> ChoosingMode : NotAvailable


ProcessingNextLegOrStartActivity --> ReleasingParkingSpot : ProcessingNextLegOrStartActivity
ProcessingNextLegOrStartActivity --> WaitingToDrive : ProcessingNextLegOrStartActivity
ProcessingNextLegOrStartActivity -[#blue,dotted]-> ChoosingMode : IntermediateTransitionState
ProcessingNextLegOrStartActivity -[#blue,dotted]-> WaitingForReservationConfirmation : IntermediateTransitionState
ProcessingNextLegOrStartActivity -[#blue,dotted]-> Waiting : IntermediateTransitionState
ProcessingNextLegOrStartActivity -[#blue,dotted]-> PerformingActivity : IntermediateTransitionState
'[*] is stop event'
ProcessingNextLegOrStartActivity -[#blue,dotted]-> [*] : IntermediateTransitionState





@enduml