@startuml

scale 1000 width
skinparam stateBorderColor #black
skinparam stateFontStyle bold
skinparam arrowColor #black

' BeamAgent: States '
state Uninitialized #grey
Uninitialized: InitializeTrigger

state Initialized #grey
Initialized: ActivityBeginTrigger

'BeamAgent Transitions'
[*] --> Uninitialized
Uninitialized -> Initialized

''''''''''''''''''''''''''
' PersonAgent States'
''''''''''''''''''''''''''
state PerformingActivity #eb1921
PerformingActivity: ActivityEndTrigger

state ChoosingMode #eb1921
ChoosingMode: BeginModeChoiceTrigger
ChoosingMode: FinalizeModeChoiceTrigger

state Traveling #eb1921{
    Traveling: OnEnter: EnterBodyVehicle
    Traveling: OnExit: ExitBodyVehicle

    state Walking #eb1921{
        Walking: Triggers:
        Walking: -PersonEntersVehicleTrigger [1]
        Walking: -PersonArrivesTransitStopTrigger [2]
        Walking: -PersonArrivalTrigger [3]
    }
    state Driving #eb1921{
        Driving: PersonExitsVehicleTrigger
    }
    state Waiting #eb1921{
        Waiting: PersonEntersBoardingQueueTrigger
    }
    state Boarding #eb1921{
        Boarding: PersonEntersVehicleTrigger
    }
    state OnTransit #eb1921{
        OnTransit: PersonEntersAlightingQueueTrigger
    }
    state Alighting #eb1921{
        Alighting: PersonExitsVehicleTrigger
    }

    [*] --> Walking
    Walking --> Driving: 1
    Walking --> Waiting: 2
    Waiting --> Boarding
    Boarding --> OnTransit
    OnTransit --> Alighting
    Alighting --> Walking
    Driving --> Walking
}

''''''''''''''''''''''''''
' PersonAgent Transitions'
''''''''''''''''''''''''''
Initialized --> PerformingActivity
PerformingActivity --> ChoosingMode
Traveling --> PerformingActivity
ChoosingMode --> ChoosingMode
ChoosingMode --> Waiting
Walking --> Traveling: 3

@enduml