@startuml
Scheduler -> PersonAgent: PersonDepartureTrigger
PersonAgent -> PersonAgent: BecomeDriver|ModifyPassengerSchedule
PersonAgent <-> Driver:SeeDriverProtocol
Scheduler -> PersonAgent: PassengerScheduleEmptyTrigger
PersonAgent -> Scheduler: ActivityEndTrigger
@enduml