@startuml
Scheduler -> PersonAgent: ActivityEndTrigger
PersonAgent -> Scheduler: ScheduleBeginModeChoiceTrigger
Scheduler -> PersonAgent: BeginModeChoiceTrigger
PersonAgent -> Household: MobilityStatusInquiry
Household -> PersonAgent: MobilityStatusReponse
PersonAgent -> Router: RoutingRequest
PersonAgent -> RideHailManager: RideHailInquiry
PersonAgent -> Scheduler: ScheduleFinalizeModeChoiceTrigger
Router -> PersonAgent: RoutingResponse
RideHailManager -> PersonAgent: RideHailingInquiryResponse
Scheduler -> PersonAgent: FinalizeModeChoiceTrigger
PersonAgent -> PersonAgent: MakeChoice
PersonAgent --> RideHailManager: ReserveRide|ReleaseVehicleReservation
RideHailManager --> PersonAgent: ReservationResponse(Success|Fail)
PersonAgent --> Drivers: ReservationRequests if Chosen
Drivers --> PersonAgent: ReservationResponses(Success|Fail)
PersonAgent --> Drivers: RemovePassengerFromTrips if AnyFailed
PersonAgent --> Household: ReleaseVehicleReservation if Unused
PersonAgent -> Scheduler: SchedulePersonDepartureTrigger
@enduml